# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://cirrus-ci.org/guide/macOS/
#   - https://cirrus-ci.org/guide/windows/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: python:3.9

env:
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"
  # Increment the build number to force new mambaforge cache upload.
  MAMBA_CACHE_BUILD: "0"
  # Increment the build number to force new mint cache upload.
  MINT_CACHE_BUILD: "0"
  # Base environment conda packages to be installed
  MAMBA_CACHE_PACKAGES: "pip conda-lock"

#
# Testing (Linux)
#
linux_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.7"
    env:
      PY_VER: "3.8"
    env:
      PY_VER: "3.9"
  name: "Linux: py${PY_VER}"
  container:
    dockerfile: requirements/ci/linux/Dockerfile
  env:
    ENV_DIR: ${HOME}/mambaforge/envs/py${PY_VER}
    PATH: ${HOME}/mambaforge/bin:${PATH}
  mamba_cache:
    folder: ${HOME}/mambaforge
    fingerprint_script:
      - wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O mambaforge.sh
      - echo "${CIRRUS_OS} $(sha256sum mambaforge.sh)"
      - echo "${MAMBA_CACHE_PACKAGES}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${MAMBA_CACHE_BUILD}"
    populate_script:
      - bash mambaforge.sh -b -p ${HOME}/mambaforge
      - conda config --set always_yes yes --set changeps1 no
      - conda config --set show_channel_urls True
      - conda config --add channels conda-forge
      - conda install --quiet --name base ${MAMBA_CACHE_PACKAGES}
  check_script:
    - conda info --all
    - conda list --name base
  mint_cache:
    folder: ${HOME}/mambaforge/envs/py${PY_VER}
    fingerprint_script:
      - echo "${CIRRUS_OS} py${PY_VER} tests"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${MINT_CACHE_BUILD}"
      - cat ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
    populate_script:
      - conda-lock --mamba --platform linux-64 --file ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
      - mamba create --name py${PY_VER} --quiet --file conda-linux-64.lock
      - cp conda-linux-64.lock ${HOME}/mambaforge/envs/py${PY_VER}
  pytest_script:
    - cat ${HOME}/mambaforge/envs/py${PY_VER}/conda-linux-64.lock >&2
    - source ${HOME}/mambaforge/etc/profile.d/conda.sh >/dev/null 2>&1
    - conda activate py${PY_VER} >/dev/null 2>&1
    - conda list
    - pip install --no-deps --editable .
    - pytest
    - mkdir build-cmake
    - cd build-cmake
    - cmake -DVTK_INCLUDE_DIR=${ENV_DIR}/include/vtk-9.0 -DVTK_LIBRARY_DIR=${ENV_DIR}/lib -DVTK_VERSION=9.0 ..
    - make
    - ctest


#
# Testing (macOS)
#
osx_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.9"
  name: "OSX: py${PY_VER}"
  osx_instance:
    image: big-sur-xcode
  env:
    ENV_DIR: ${HOME}/mambaforge/envs/py${PY_VER}
    PATH: ${HOME}/mambaforge/bin:${PATH}
  mamba_cache:
    folder: ${HOME}/mambaforge
    fingerprint_script:
      - wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-x86_64.sh -O mambaforge.sh
      - echo "${CIRRUS_OS} $(shasum -a 256 mambaforge.sh)"
      - echo "${MAMBA_CACHE_PACKAGES}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${MAMBA_CACHE_BUILD}"
    populate_script:
      - bash mambaforge.sh -b -p ${HOME}/mambaforge
      - conda config --set always_yes yes --set changeps1 no
      - conda config --set show_channel_urls True
      - conda config --add channels conda-forge
      - conda install --quiet --name base ${MAMBA_CACHE_PACKAGES}
  check_script:
    - conda info --all
    - conda list --name base
  mint_cache:
    folder: ${HOME}/mambaforge/envs/py${PY_VER}
    fingerprint_script:
      - echo "${CIRRUS_OS} py${PY_VER} tests"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${MINT_CACHE_BUILD}"
      - cat ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
    populate_script:
      - conda-lock --mamba --platform osx-64 --file ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
      - mamba create --yes --name py${PY_VER} --quiet --file conda-osx-64.lock
      - cp conda-osx-64.lock ${HOME}/mambaforge/envs/py${PY_VER}
  test_script:
    - cat ${HOME}/mambaforge/envs/py${PY_VER}/conda-osx-64.lock >&2
    - source ${HOME}/mambaforge/etc/profile.d/conda.sh >/dev/null 2>&1
    - conda activate py${PY_VER} >/dev/null 2>&1
    - pip install --no-deps --editable .
    - pytest
    - mkdir build-cmake
    - cd build-cmake
    - cmake -DBUILD_FORTRAN=OFF -DVTK_INCLUDE_DIR=${ENV_DIR}/include/vtk-9.0 -DVTK_LIBRARY_DIR=${ENV_DIR}/lib -DVTK_VERSION=9.0 ..
    - make VERBOSE=1 # link error 
    - ctest

#
# Testing (Windows)
#
win_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.9"
  name: "Windows: py$PY_VER"
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  env:
    # use $VAR not %VAR%
    CONDA_DIR: $USERPROFILE\miniconda3
    CONDA_LIB: $CONDA_DIR\Library
    PATH: $CONDA_DIR;$CONDA_LIB\bin;$CONDA_DIR\Scripts;$CONDA_DIR\condabin;$PATH
    # must set this to its default since it doesn't work in env variables
    # see https://github.com/cirruslabs/cirrus-ci-docs/issues/423
    CIRRUS_WORKING_DIR: C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build
    PYTHON_ARCH: 64
  conda_script:
    - choco install -y miniconda3 --params="'/D:%CONDA_DIR%'"
    - conda update -yn base conda
    - conda install -c conda-forge setuptools
    - conda install --yes python=%PY_VER%
    - conda install --yes pytest tbb cython numpy
    - conda install --yes -c conda-forge vtk=9.0.3 libnetcdf
  install_script:
    - conda list
    - pip install --no-deps --editable .    
    - python -c "import mint; print(dir(mint))"
    - cd mint\tests
    - python test_grid.py
    - python test_polyline_integral.py
    - python test_regrid_edges.py
    - python test_vector_interp.py
    - pytest
    # - ps: Get-Command python
    # - echo %PATH%
    # - dir C:\Users\ContainerAdministrator\miniconda3\Library\bin
    # - dir C:\Users\ContainerAdministrator\miniconda3\Library\bin\vtkRendering*.dll
    # - python -c "import vtk"
  test_script:
    - mkdir build-cmake
    - cd build-cmake
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    - where cl
    - cmake -G "NMake Makefiles" -DBUILD_FORTRAN=OFF -DVTK_INCLUDE_DIR=%CONDA_DIR%\Library\include\vtk-9.0 -DVTK_LIBRARY_DIR=%CONDA_DIR%\Library\lib -DNETCDF_INCLUDE_DIRS="%CONDA_DIR%\Library\include" -DNETCDF_LIBRARIES="%CONDA_DIR%\Library\lib\netcdf.lib" ..
    - nmake
    - ctest
