#ifndef MNT_GLOBAL
#define MNT_GLOBAL

#define MNT_CELL_BY_CELL_DATA 0
#define MNT_UNIQUE_EDGE_DATA 1
#define MNT_NUM_EDGES_PER_QUAD 4
#define MNT_NUM_VERTS_PER_QUAD 4
#define MNT_NUM_VERTS_PER_EDGE 2
#define MNT_FUNC_SPACE_W1 1
#define MNT_FUNC_SPACE_W2 2
#define MNT_GEO_CARTESIAN 0
#define MNT_GEO_SPHERICAL 1

#endif // MNT_GLOBAL