name: CMake on multiple platforms

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    #
    # Ubuntu dependencies
    #
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnetcdf-dev \
          libvtk9-dev

    #
    # Windows dependencies via vcpkg
    #
    - name: Setup vcpkg
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitHubToken: 'f3e10653cc27d62a37a3763cd84b38bca07c6075' # recent commit at 
        vcpkgDirectory: C:/vcpkg

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        vcpkg install netcdf-c:x64-windows
        vcpkg install vtk:x64-windows

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libnetcdf-dev \
          libvtk9-dev \
          libgl1-mesa-dev \
          libxt-dev \
          qtbase5-dev \
          qttools5-dev \
          libqt5x11extras5-dev

    - name: Configure CMake
      run: >
        cmake
        -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        ${{ runner.os == 'Windows' &&
            '-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake'
            || '' }}

    - name: Build
      run: >
        cmake --build
        ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: >
        ctest
        --build-config ${{ matrix.build_type }}
        --output-on-failure
