name: Install and Test Python Bindings

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: mint-env
          auto-activate-base: false
          python-version: "3.12"
          channels: conda-forge
          channel-priority: strict

      - name: Install dependencies
        run: |
          conda install -y \
            cmake \
            cython \
            setuptools \
            tbb-devel \
            pip \
            libnetcdf \
            vtk \
            numpy \
            pytest \
            netcdf4 \
            iris \
            cxx-compiler

      - name: Install mint Python bindings
        run: |
          export CC="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-cc"
          export CXX="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-c++"
          pip install .

      - name: Run tests
        run: pytest
